export const CUSTOMERS = [
    {
        id: 1,
        avatar: "",
        name: "John",
        surname: "Doe",
        company: "Doe Inc.",
        status: "Active",
        plan: "Basic",
        registrationDate: "2022-01-01",
    },
    {
        id: 2,
        avatar: "",
        name: "Jack",
        surname: "William",
        company: "Klar Inc.",
        status: "Active",
        plan: "Pro",
        registrationDate: "2023-05-18",
    },
    {
        id: 3,
        avatar: "",
        name: "Nelly",
        surname: "Perkins",
        company: "Smith Inc.",
        status: "Active",
        plan: "Enterprise",
        registrationDate: "2018-03-08",
    },
    {
        id: 4,
        avatar: "",
        name: "Chuck",
        surname: "Norris",
        company: "Some Inc.",
        status: "Inactive",
        plan: "Pro",
        registrationDate: "2022-05-18",
    },
    {
        id: 5,
        avatar: "",
        name: "Lara",
        surname: "Carlson",
        company: "Opus Ltd.",
        status: "Active",
        plan: "Basic",
        registrationDate: "2024-01-13",
    },

];