export const PRODUCTS = [
    {
        id: 1,
        name: "Product 1",
        category: "Subscription",
        price: 100,
        status: "Active",
        totalSales: 100,
    },
    {
        id: 2,
        name: "Product 2",
        category: "Add-ons",
        price: 200,
        status: "Inactive",
        totalSales: 200,
    },
    {
        id: 3,
        name: "Product 3",
        category: "Service",
        price: 300,
        status: "Active",
        totalSales: 300,
    },
    {
        id: 4,
        name: "Product 4",
        category: "Subscription",
        price: 400,
        status: "Inactive",
        totalSales: 400,
    },
    {
        id: 5,
        name: "Product 5",
        category: "Add-ons",
        price: 500,
        status: "Active",
        totalSales: 500,
    },
    {
        id: 6,
        name: "Product 6",
        category: "Service",
        price: 600,
        status: "Inactive",
        totalSales: 600,
    },
    {
        id: 7,
        name: "Product 7",
        category: "Subscription",
        price: 700,
        status: "Active",
        totalSales: 700,
    },
    {
        id: 8,
        name: "Product 8",
        category: "Add-ons",
        price: 800,
        status: "Inactive",
        totalSales: 800,
    },
    {
        id: 9,
        name: "Product 9",
        category: "Service",
        price: 900,
        status: "Active",
        totalSales: 900,
    },
    {
        id: 10,
        name: "Product 10",
        category: "Subscription",
        price: 1000,
        status: "Inactive",
        totalSales: 1000,
    },
];